version: '3.8'

services:
  servidor:
    build:
      context: .
      dockerfile: Dockerfile.servidor
    container_name: servidor
    privileged: true
    networks:
      rede_sd:
        ipv4_address: 100.0.0.1
  cliente1:
    build:
      context: .
      dockerfile: Dockerfile.cliente
    container_name: cliente1
    privileged: true
    networks:
      rede_sd:
        ipv4_address: 100.0.0.2
  cliente2:
    build:
      context: .
      dockerfile: Dockerfile.cliente
    container_name: cliente2
    privileged: true
    networks:
      rede_sd:
        ipv4_address: 100.0.0.3
networks:
  rede_sd:
    driver: bridge
    ipam:
      config:
        - subnet: 100.0.0.0/24